Select * from customer limit 20

--Q1.What is the total revenue generated by male vs. female customers?
Select gender,sum(purchase_amount) as revenue 
from customer
group by gender

--Q2.Which customer used a discount but still spent more than the average purchase amount
Select customer_id,purchase_amount
from customer
where discount_applied='Yes' and purchase_amount >=(
Select Avg(purchase_amount) from customer)

--Q3.Which are the top 5 products with the highest
Select item_purchased,Round(Avg(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

--Q4.Compare the average purchase amount between standard and express shipping
Select shipping_type,
Round(Avg(purchase_amount::numeric),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

--Q5.Do subscribed customers spend more?Compare average spend and total revenue between 
--subscribers and non-subscribers
Select subscription_status,
count(customer_id) as total_customers,
Round(avg(purchase_amount::numeric),2) as avg_spend,
Round(sum(purchase_amount::numeric),2) as total_revenue
from customer
group by subscription_status
order by total_revenue,avg_spend desc;

--Q6.Which 5 products have the highest percentage of purchases with discount applied?
Select item_purchased,
Round(100*sum(case when discount_applied='Yes' Then 1
Else 0 End)/count(*),2) as discount_rate
from customer
group by item_purchased 
order by discount_rate desc
limit 5;

--Q7.Segment customers into New,Returning and Loyal based on their total number of previous 
--purchases,and show the count of each segment
with customer_type as(
Select customer_id,previous_purchases,
Case when previous_purchases=1 Then 'New'
	 when previous_purchases Between 2 and 10 Then 'Returning'
	 Else 'Loyal'
	 End as customer_segment
from customer
)

Select customer_segment,count(*) as "Number of Customers"
from customer_type
group by customer_segment
)

--Q8.What are the top 3 most purchased products within each category
with item_counts as(
Select category,item_purchased,
Count(customer_id) as total_orders,
Row_Number() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category,item_purchased
)

Select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank<=3;

--Q9.Are customers who are repeat buyers(more than 5 previous purchases) also likely
--to subscribe?
Select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status;

--Q10.What is the revenue contribution of each age group?
Select age_group,
Sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;